alias j="jobs"
alias df="df -k"
alias du="du -k"
alias ls='ls --color'
alias la="ls -a"
alias ll="ls -l"
alias vi=/usr/bin/vim
alias vim=/usr/bin/nvim
alias grep="grep --color"
alias outline="grep --color '^class \|def '"
alias sa='source $HOME/mc/bin/activate'
alias sd='source $HOME/mc/bin/deactivate'
alias conda='$HOME/mc/bin/conda'
